name: CI

env:
  ELIXIR_VERSION: "1.18"
  OTP_VERSION: "27"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests-and-code-quality:
    runs-on: ubuntu-24.04
    name: Tests and Code Quality
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1
        id: beam
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Restore dependencies and build cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-otp-${{ steps.beam.outputs.otp-version }}-elixir-${{ steps.beam.outputs.elixir-version }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-otp-${{ steps.beam.outputs.otp-version }}-elixir-${{ steps.beam.outputs.elixir-version }}-
      - name: Restore PLT cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        id: plt_cache
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-plt-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-plt-
          path: |
            .plts
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Compile
        run: mix compile --warnings-as-errors
      - name: Run Formatter
        run: mix format --check-formatted
      - name: Run Linter
        run: mix credo
      - name: Run Hex Audit
        run: mix hex.audit
      - name: Run Mix Audit
        run: mix deps.audit
      - name: Run Tests
        run: mix coveralls.json --warnings-as-errors
      - uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          files: ./cover/excoveralls.json
      - name: Run Dialyzer
        run: mix dialyzer
